spring:
  application:
    name: myProducts
  datasource:
#    url: jdbc:postgresql://localhost:5432/myProducts
#    username: postgres
#    password: postgres
    url: ${SPRING_DB_HOST}
    username: ${SPRING_DB_USER}
    password: ${SPRING_DB_USER}
  jpa:
    hibernate:
      ddl-auto: update